### ISSUE TITLE
ForeignKey in resource: AttributeError: 'str' object has no attribute '_saved_in_db'

### ISSUE THREAD

**Issue by MalikDeveloper2077** [long2ice/fastapi-admin#89]
```python
class Category(CoreModel):
    parent = fields.ForeignKeyField('models.Category', related_name='children', null=True)

class CategoryResource(CustomModel):
    fields = [..., Field('parent', input_=inputs.ForeignKey(Category, null=True))]
```

 I added the input to do the nullable field, now I can create an object with blank input, but I **can't** create an object with **selected parent** and get that error:
 ```
web      | Traceback (most recent call last):
web      |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
web      |     result = await app(self.scope, self.receive, self.send)
web      |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
web      |     return await self.app(scope, receive, send)
web      |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
web      |     await super().__call__(scope, receive, send)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
web      |     await self.middleware_stack(scope, receive, send)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
web      |     raise exc from None
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
web      |     await self.app(scope, receive, _send)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
web      |     await self.simple_response(scope, receive, send, request_headers=headers)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
web      |     await self.app(scope, receive, send)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
web      |     raise exc from None
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
web      |     await self.app(scope, receive, sender)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
web      |     await route.handle(scope, receive, send)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 390, in handle
web      |     await self.app(scope, receive, send)
web      |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
web      |     await super().__call__(scope, receive, send)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
web      |     await self.middleware_stack(scope, receive, send)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
web      |     raise exc from None
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
web      |     await self.app(scope, receive, _send)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
web      |     response = await self.dispatch_func(request, self.call_next)
web      |   File "/usr/local/lib/python3.9/site-packages/fastapi_admin/providers/login.py", line 135, in authenticate
web      |     response = await call_next(request)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
web      |     task.result()
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
web      |     await self.app(scope, receive, send)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
web      |     response = await self.dispatch_func(request, self.call_next)
web      |   File "/usr/local/lib/python3.9/site-packages/fastapi_admin/middlewares.py", line 19, in language_processor
web      |     response = await call_next(request)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
web      |     task.result()
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
web      |     await self.app(scope, receive, send)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
web      |     raise exc from None
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
web      |     await self.app(scope, receive, sender)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
web      |     await route.handle(scope, receive, send)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
web      |     await self.app(scope, receive, send)
web      |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
web      |     response = await func(request)
web      |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 219, in app
web      |     raw_response = await run_endpoint_function(
web      |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 152, in run_endpoint_function
web      |     return await dependant.call(**values)
web      |   File "/usr/local/lib/python3.9/site-packages/fastapi_admin/routes/resources.py", line 211, in create
web      |     obj = await model.create(**data, using_db=conn)
web      |   File "/usr/local/lib/python3.9/site-packages/tortoise/models.py", line 1102, in create
web      |     instance = cls(**kwargs)
web      |   File "/usr/local/lib/python3.9/site-packages/tortoise/models.py", line 655, in __init__
web      |     for key in meta.fields.difference(self._set_kwargs(kwargs)):
web      |   File "/usr/local/lib/python3.9/site-packages/tortoise/models.py", line 670, in _set_kwargs
web      |     if value and not value._saved_in_db:
web      | AttributeError: 'str' object has no attribute '_saved_in_db'
```

**Comment by WojtekNosal** [comment]
I have exactly the same problem, @MalikDeveloper2077 did you manage to solve it somehow?

**Comment by MalikDeveloper2077** [comment]
@WojtekNosal Hello, not yet

**Comment by WojtekNosal** [comment]
@MalikDeveloper2077 a bit hacky but I've managed to get it working:
 
 add custom fk input
```python
from fastapi_admin.widgets.inputs import ForeignKey
from starlette.requests import Request


class CustomForeignKey(ForeignKey):
    async def parse_value(self, request: Request, value: Any):
        is_nullable = self.context.get("null", False) is True
        if not value and is_nullable:
            return None
        model = self.model
        field_pk_attr = model._meta.pk_attr
        obj = await model.get(**{field_pk_attr: value})
        return obj
```

then in your model just use new input:

```python
Field(
    name="name",
    label="Some label",
    input_=CustomForeignKey(MyModel, default=None, null=True),
 ),
```
